# Generated by Django 5.2.12 on 2026-03-21 12:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('subject', config='english', weight='A'), '||', django.contrib.postgres.search.SearchVector('body_clean', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), '||', django.contrib.postgres.search.SearchVector('body_text', config='english', weight='C'), django.contrib.postgres.search.SearchConfig('english')), name='message_fts_gin_idx'),
        ),
    ]
